### ISSUE TITLE
[BUG] Icon missing on Image Viewer (eog) About screen in Rawhide Silverblue

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#306]
**Describe the bug**
In recent Rawhide Silverblue builds (I'm guessing after Fedora-Rawhide-20220621.n.3, but for certain from Fedora-Rawhide-20220628.n.0), the icon that should be shown on the About screen in Image Viewer (eog) is missing.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install a recent Rawhide Silverblue, e.g. https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20220628.n.0/compose/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-Rawhide-20220628.n.0.iso
2. Boot it, run Image Viewer, and open the About screen

**Expected behavior**
Above "Image Viewer", a proper icon should be displayed, instead a placeholder icon is shown.

**Screenshots**
![badabout](https://user-images.githubusercontent.com/916551/176318746-0b23a6d2-0162-4763-aa12-f6a7e53454a0.png)

**Comment by Honza0297** [comment]
Hello and thanks for reporting! I'll take a look and fix it.

**Comment by AdamWill** [comment]
Still happening, BTW.

**Comment by lruzicka** [comment]
I also reported this to Eye of Gnome, but they think the problem is not at their part (https://gitlab.gnome.org/GNOME/eog/-/issues/254#note_1534039).
According to the list of packages in the compose, the version of `eog` should have been `43.beta` but the dialogue reports `42.1`, maybe the problem is not just a missing icon, but something in the background.

**Comment by tpopela** [comment]
@lruzicka no, the version should be 42.x as Fedora Flatpaks are always based on the latest *stable* release of Fedora and not 43.beta (aka rawhide/F37). So this is definitely expected.

**Comment by lruzicka** [comment]
> @lruzicka no, the version should be 42.x as Fedora Flatpaks are always based on the latest _stable_ release of Fedora and not 43.beta (aka rawhide/F37). So this is definitely expected.

Ok, I did not know that. Thanks for the information.

**Comment by tpopela** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2022-6e191c5e67 should fix it (build done by @Honza0297 )

**Comment by lruzicka** [comment]
Currently still happening on 
~~~
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20220824.n.2 (2022-08-24T16:25:36Z)
                   Commit: 382dddfd5973a1a320a25ee7321c2db1bc7f635c035d44f10e5d6de72c61f1b9
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
~~~

**Comment by lruzicka** [comment]
@tpopela 

~~~
[test@fedora ~]$ flatpak info org.gnome.eog

Image Viewer - Browse and rotate images

           ID: org.gnome.eog
          Ref: app/org.gnome.eog/x86_64/stable
         Arch: x86_64
       Branch: stable
      Version: 42.1
      License: GPL-2.0+ and GFDL-1.3
       Origin: fedora
   Collection: 
 Installation: system
    Installed: 12.7 MB
      Runtime: org.fedoraproject.Platform/x86_64/f36
          Sdk: org.fedoraproject.Sdk/x86_64/f36

Active commit: 104cdd41094605357d0b9d6ef6218b4f7d6062724e9d8fcb8795ec1762955db8
Latest commit: ref not present in origin
      Subject: Export org.gnome.eog
         Date: 2022-05-17 15:46:26 +0000
       Alt-id: cc985234834498a54ab24324a877a287ee467c183e2e5e7c1d84bae09bfdbbe0
~~~

It seems it is still using the old version, but I have updated what I could:

1. System `rpm-ostree update`
2. Flatpaks `flatpak update`

I am still running the older version.

**Comment by tpopela** [comment]
You will need to enable the fedora-testing Flatpak remote to get the update once it's pushed there - if you look at the Bodhi link then you can see there that it's still being pushed there.

**Comment by tpopela** [comment]
@lruzicka as you didn't add the remote as the system one, you need to use `flatpak --user remotes` to view it. The same applies for installing from it - you have to pass `--user` to `flatpak` so it can see it.

**Comment by lruzicka** [comment]
> @lruzicka as you didn't add the remote as the system one, you need to use `flatpak --user remotes` to view it. The same applies for installing from it - you have to pass `--user` to `flatpak` so it can see it.

I though that using `sudo` will do it ...?

**Comment by tpopela** [comment]
The eog update hit the stable repositories and I can confirm that the issue is fixed.

**Comment by lruzicka** [comment]
I have updated the EoG on the latest Silverblue and it seems to fixed indeed. Thanks a lot.
