### ISSUE TITLE
Unable to upgrade with wireshark layered

### ISSUE THREAD

**Issue by mrpaulblack** [fedora-silverblue/issue-tracker#50]
I layered Wireshark with rpm-ostree install wireshark and added my user account to the Wireshark group with the workaround from the silverblue docs (https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/). After a restart everything worked fine.
But a day after that I tried to upgrade my system with rpm-ostree upgrade and the following error occurred: error: While applying overrides for pkg wireshark-cli: Could not find group 'wireshark' in group file.
Thats the line in question in my /etc/group file: wireshark:x:969:local.

THe only workaround for this seems to be to rpm-ostree uninstall wireshark.

**Comment by tpopela** [comment]
@dustymabe @cgwalters any idea?

**Comment by felipehw** [comment]
There is some discussion here:  https://discussion.fedoraproject.org/t/overlay-wireshark-upgrade-broken/25407/18

But the problem remains:

```
$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220606.0 (2022-06-06T01:47:39Z)
                BaseCommit: 421ae524f62d85d1ce9398cee5e63b661e48dbce408c290283dc7aff467d39e3
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 101.0-1.fc36
           LayeredPackages: akmod-nvidia code containerd.io docker-ce docker-ce-cli docker-compose-plugin fish gnome-console gnome-tweak-tool lollypop rpmfusion-free-release
                            rpmfusion-nonfree-release seahorse-nautilus simple-scan wireshark xorg-x11-drv-nvidia

  fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220606.0 (2022-06-06T01:47:39Z)
                BaseCommit: 421ae524f62d85d1ce9398cee5e63b661e48dbce408c290283dc7aff467d39e3
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 101.0-1.fc36
           LayeredPackages: akmod-nvidia code containerd.io docker-ce docker-ce-cli docker-compose-plugin fish gnome-console gnome-tweak-tool lollypop rpmfusion-free-release
                            rpmfusion-nonfree-release seahorse-nautilus simple-scan xorg-x11-drv-nvidia
                    Pinned: yes
$ rpm-ostree update                                                                                                                       0.712s 20:34
⠙ Receiving metadata objects: 1/(estimating) 196 bytes/s 196 bytes... 
Receiving metadata objects: 1/(estimating) 196 bytes/s 196 bytes... done
Checking out tree 7e15d96... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree code docker-ce-stable updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-04-07T16:52:38Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2022-05-04T21:12:01Z solvables: 825
rpm-md repo 'updates-modular' (cached); generated: 2022-06-03T03:02:32Z solvables: 1153
rpm-md repo 'updates' (cached); generated: 2022-06-07T02:15:46Z solvables: 12120
rpm-md repo 'fedora' (cached); generated: 2022-05-04T21:16:11Z solvables: 67992
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2022-06-07T07:02:38Z solvables: 49
rpm-md repo 'rpmfusion-free' (cached); generated: 2022-05-04T04:48:11Z solvables: 506
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2022-06-07T07:21:57Z solvables: 29
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2022-05-04T05:11:55Z solvables: 225
rpm-md repo 'code' (cached); generated: 2022-06-07T20:17:21Z solvables: 2243
rpm-md repo 'docker-ce-stable' (cached); generated: 2022-06-07T00:44:36Z solvables: 14
rpm-md repo 'updates-archive' (cached); generated: 2022-06-07T02:35:41Z solvables: 12759
Resolving dependencies... done
Applying 1 override and 211 overlays
Processing packages... done
Running pre scripts... done
Running post scripts... done
error: While applying overrides for pkg wireshark-cli: Could not find group 'wireshark' in group file
$ 
```

**Comment by travier** [comment]
We've merged the fix in https://src.fedoraproject.org/rpms/wireshark/pull-request/6. Hopefully that's enough to fix the issue. Please comment again here if that's not the case. Thanks!

**Comment by abegert** [comment]
Hi, hope it's okay to revive this. I still have the same problem on Fedora Silverblue 37. wireshark is currently at 4.0.1.

What can I do about this? Apart from the workaround of uninstalling wireshark, upgrading the system and installing it again?

**Comment by NoMore201** [comment]
Still the same issue here on Silverblue 39, package version (`rpm-ostree status`) is `39.20231222.0`. Wireshark group is present in both `/etc/group` and `/usr/lib/group`, but I guess ostree does something under the hood that I don't know.

**Comment by travier** [comment]
Alternatives in https://discussion.fedoraproject.org/t/silverblue-wireshark-does-not-see-network-interfaces/88916/11 until this is resolved.

**Comment by JoeMcNuggets** [comment]
Any updates on this issue?

**Comment by travier** [comment]
As another alternative, I've made a system extension for Wireshark: https://github.com/travier/fedora-sysexts/pull/59

**Comment by travier** [comment]
This should be fixed with the move to sysusers support in RPM. Please comment here if this is still happening. Thanks.

**Comment by travier** [comment]
A build of rpm-ostree with the fix hasn't landed in a Silverblue update yet.

**Comment by travier** [comment]
OK, I got that mixed up with https://github.com/coreos/rpm-ostree/issues/5494. Can you open a new issue here and provide all the details asked?
